/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ImpactMappingRouteImport } from './routes/impact-mapping'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as BackgroundRouteImport } from './routes/background'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as ModelsSlugRouteImport } from './routes/models/$slug'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactMappingRoute = ImpactMappingRouteImport.update({
  id: '/impact-mapping',
  path: '/impact-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRoute = BackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/conclusion': typeof ConclusionRoute
  '/impact-mapping': typeof ImpactMappingRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/conclusion': typeof ConclusionRoute
  '/impact-mapping': typeof ImpactMappingRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/models': typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/conclusion': typeof ConclusionRoute
  '/impact-mapping': typeof ImpactMappingRoute
  '/methodology': typeof MethodologyRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background'
    | '/conclusion'
    | '/impact-mapping'
    | '/methodology'
    | '/models/$slug'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background'
    | '/conclusion'
    | '/impact-mapping'
    | '/methodology'
    | '/models/$slug'
    | '/models'
  id:
    | '__root__'
    | '/'
    | '/background'
    | '/conclusion'
    | '/impact-mapping'
    | '/methodology'
    | '/models/$slug'
    | '/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRoute: typeof BackgroundRoute
  ConclusionRoute: typeof ConclusionRoute
  ImpactMappingRoute: typeof ImpactMappingRoute
  MethodologyRoute: typeof MethodologyRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-mapping': {
      id: '/impact-mapping'
      path: '/impact-mapping'
      fullPath: '/impact-mapping'
      preLoaderRoute: typeof ImpactMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRoute: BackgroundRoute,
  ConclusionRoute: ConclusionRoute,
  ImpactMappingRoute: ImpactMappingRoute,
  MethodologyRoute: MethodologyRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
